Repository recodehive/Scrape-ML, pull requests merged in 2024-05, with the labels that each got.

#8 School List using Web Scrapping
  .github/workflows/greetings.yml
  School_Web Scrapping.ipynb
Labels: gssoc, level2

#19 Enhanced documentation
  README.md
Labels: gssoc

#20 Update README.md #11
  README.md
Labels: gssoc

#25 Added Clustering for Product Listings
  .vscode/settings.json
  Product listing.csv
  clustering movie review.ipynb
  data.csv
Labels: gssoc, level2

#26 #Filtering movie tags and movie review mails
  Movie_review_imdb_scrapping.ipynb
Labels: gssoc, level2

#32 Update README.md
  README.md
Labels: good first issue, gssoc

#39 Template to report_bug.md
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: gssoc, level1

#40 Create feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: gssoc, level1

#43 README Updated
  README.md
  amazon_scrapping/README.md
Labels: gssoc

#46 Zomato web scrape for banglore location using selenium
  zomato-webscrape/Blr.csv
  zomato-webscrape/web scrape_zomato.ipynb
Labels: gssoc, level2

#50 Added Python News Data Scrapping (Issue: #33)
  News_data_scrapping/README.md
  News_data_scrapping/code.py
Labels: gssoc, level2

#53 Added Sentimental Analysis Code #13
  Movie_review_imdb_scrapping.ipynb
Labels: gssoc, level2

#59 Scrapped Used Car details and Price data
  Scrapped_Used_Car_data/Data/test.csv
  Scrapped_Used_Car_data/Data/train.csv
  Scrapped_Used_Car_data/Scrapping/used_car.csv
  Scrapped_Used_Car_data/Scrapping/used_car_scrapping.py
Labels: gssoc, level1

#74 #36
  amazon_scrapping/sentiment_analysis_33.ipynb
Labels: gssoc, level1

#75 Revert "Create feature_request.md"
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: gssoc, level1

#80 Add error handling, Change in clusters
  .ipynb_checkpoints/clustering movie review-checkpoint.ipynb
Labels: gssoc, level1

#82 documentation for ocr software done
  Documentation/Documentation for Scrapping using ocr
  Scrap_ml_ocr.zip
Labels: gssoc, level2

#89 added auto commenting feat for PR merged
  .github/workflows/autocomment-pr-merge.yml
Labels: gssoc, level1

#91 Added pull_request_template.md
  .github/pull_request_template.md
Labels: gssoc

#93 Add Streamlit web app for IMDb movie review analysis and recommendations
  Web_app/__pycache__/utils.cpython-311.pyc
  Web_app/app.py
  Web_app/instructions.txt
  Web_app/utils.py
Labels: gssoc

#96 Added README File for Web_app Folder
  Web_app/README.md
  Web_app/instructions.txt
Labels: gssoc, level1

#98 Made Movie Recommender System
  Movie Recommender(Beginner) /Movie Recommender
  Movie_Reccomender.ipynb
Labels: gssoc, level3

#107 Fixed git issue, cleaned data and added requirements.txt #106
  Movie Recommender(Beginner) /Movie Recommender
  data_scrapped/cleaned_data.csv
  requirements.txt
  scripts/data_preprocessing.py
Labels: gssoc, level1

#108 Clustering movie summaries added
  backlog/ClusteringOfIMDBMovies.py
Labels: gssoc, level2

#110 Collaborate
  backlog/ClusteringOfIMDBMovies.py
Labels: gssoc, level2

#114 created close-on-merge.yml
  .github/workflows/close-on-merge.yml
Labels: gssoc, level1

#115 added dependency file
  Web_app/requirements.txt
Labels: gssoc, level1

#111 created close-old-issue.yml
  .github/workflows/close-old-issue.yml
Labels: gssoc, level1

#119 Update autocomment-pr-merge.yml
  .github/workflows/autocomment-pr-merge.yml
Labels: bug, gssoc

#113 created autocomment-iss-close.yml
  .github/workflows/autocomment-iss-close.yml
Labels: gssoc, level1

#122 A model to categorize medical abstracts as objectives, background, methods, results and conclusions
  abstract_training.ipynb
Labels: gssoc, level1

#128 Update README.md [Redesign README Image]
  README.md
Labels: documentation, good first issue, gssoc, level1

#127 Fixed 'user_review' issue in streamlit app
  Web_app/streamlit_app.py
Labels: gssoc, level1

#132 Movie Genre prediction complete. Resolves [#92]
  backlog/Movie-genre-prediction/Movie-Genre-Prediction.ipynb
Labels: gssoc, level1

#137 Sentimental Analysis using Amazon reviews dataset
  amazon_scrapping/Dataset-Amazon_Reviews.csv
  amazon_scrapping/Sentiment_Analysis.ipynb
Labels: gssoc, level2
