Repository recodehive/Scrape-ML, pull requests merged in 2024-10, with the labels that each got.

#232 Fixed self call and made dataframe start from 1
  Web_app/pages/2_Movie_Recommendation.py
Labels: hacktoberfest-accepted, gssoc-ext

#235 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: level1, hacktoberfest-accepted, gssoc-ext

#256 Add git contributors to the page
  Web_app/pages/GitContributors.py
Labels: level2, hacktoberfest-accepted, gssoc-ext

#255 ADD Review Submission Page and API Documentation Page
  Web_app/movie_reviews.csv
  Web_app/pages/API_Documentation.py
  Web_app/pages/ReviewSubmission.py
Labels: level2, hacktoberfest-accepted, gssoc-ext

#263 Add polls for Movie
  Web_app/__pycache__/utils.cpython-38.pyc
  Web_app/pages/MoviePol.py
  Web_app/pollmovies.csv
Labels: level2, gssoc-ext, hacktoberfest

#286 Add fav movie page
  Web_app/pages/Favorite_Movie.py
Labels: level1, hacktoberfest-accepted, gssoc-ext

#290 Update README.md ADDED HACKTOBERFEST AND GSSOC BANNER ON THE README
  README.md
Labels: level1, hacktoberfest-accepted, gssoc-ext

#293 #292 : Updated README.md to run the application
  README.md
Labels: level1, hacktoberfest-accepted, gssoc-ext, hacktoberfest
