Repository recodehive/Scrape-ML, pull requests merged in 2024-06, with the labels that each got.

#151 Streamlit WebApp Updated and Added a new part of Content-Based Recommendation System
  Web_app/Home_Page.py
  Web_app/README.md
  Web_app/Scarper.py
  Web_app/model.ipynb
  Web_app/movies.csv
  Web_app/pages/1_Movie_Analysis.py
  Web_app/pages/2_Movie_Recommendation.py
  Web_app/requirements.txt
Labels: gssoc, level2

#147 Added Learn.md File
  Learn.md
  image-1.png
  image-2.png
  image.png
Labels: gssoc, level1

#158 Added data preprocessing (cleaning, stemming) and visualizations to amazon_scrapping/Sentiment_Analysis.ipynb
  amazon_scrapping/Sentiment_Analysis.ipynb
Labels: gssoc, level1

#156 clustering movie data from imdb issue #153
  main.py
Labels: gssoc, level1

#155 Fixing Issue #54
  CODE_OF_CONDUCT.md
Labels: good first issue, gssoc, level1

#162 Adding Updated_Scrapper.py
  Web_app/Updated_Scrapper.py
Labels: gssoc, level1

#154 Add another dataset other than IMDB
  Movie_review_rotten_tomatoes.ipynb
  data_scrapped/data_rotten_tomatoes.csv
Labels: gssoc, level1

#164 Gui interface added
  amazon_scrapping/Gui_ocr.py
Labels: gssoc, level2

#165 Updated Movie Analysis Page
  .gitignore
  Web_app/Movie_Animated.json
  Web_app/__pycache__/utils.cpython-312.pyc
  Web_app/pages/1_Movie_Analysis.py
  Web_app/requirements.txt
Labels: gssoc, level1

#170 Added issues template for documentation issues
  .github/ISSUE_TEMPLATE/documentation.md
Labels: gssoc, level1

#179 Smart select feature gui created
  Smart_select features/smart_select_gui.py
Labels: gssoc, level3

#136 Review Emotion Analysis
  Emotion Anaylisis/EmotionAnalysis.ipynb
  Emotion Anaylisis/NRC-Emotion-Lexicon-Wordlevel-v0.92.txt
  Emotion Anaylisis/README.md
  IMDB/train/neg/neg.csv
  IMDB/train/pos/pos.csv
  IMDB/train/unsup/unsup.csv
Labels: gssoc, level2

#175 Fix the streamlit app
  Web_app/__pycache__/utils.cpython-311.pyc
  Web_app/pages/1_Movie_Analysis.py
  Web_app/utils.py
Labels: gssoc, level2

#181 Update scrapping.py
  amazon_scrapping/scrapping.py
Labels: gssoc, level1

#184 Fixing File Not Found Error indicating that the file similarity.pkl could not be found
  Web_app/pages/2_Movie_Recommendation.py
  Web_app/pages/similarity.pkl
Labels: gssoc, level1

#189 Add movie genre classification
  Movie Genre Classification/Movie_genre_classification.ipynb
  Movie Genre Classification/README.MD
Labels: duplicate, wontfix, gssoc

#195 Added tags workflow flow for issues
  .github/workflows/issues-tags.yml
Labels: gssoc, level1

#203 Earthquake prediction
  README (1).md
  earthquake.ipynb
  results.csv
Labels: gssoc, level1

#205 Update scrapping.py
  amazon_scrapping/scrapping.py
Labels: gssoc, level1
